### ISSUE TITLE
[FALSE-POSITIVE] login.microsoftonline.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/whitelist#104]
**Domains or links**

- `login.microsoftonline.com`

Whitelisted unter [DShield.org-Suspicious-Domain-List/.../whitelisted.list](https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List/blob/master/whitelisted.list) but not reachable, it is also in the domains0: [mitchellkrogza/Ultimate.Hosts.Blacklist/.../domains0.list](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/domains/domains0.list)

**Additional context**

Think it's a internal problem; see above.

**Comment by dnmTX** [comment]
@Somebodyisnobody  `DShield.org's` list was just removed from upstream but will remain in filtering for a couple more days(after that will be completely gone).If it's something urgent on your end i can whitelist it,if not just wait a bit. Let me know.

P.S. See #103 just for reference and more info.

**Comment by Somebodyisnobody** [comment]
Oh thank you, I already whitelisted it on my end :). So let's wait
