### ISSUE TITLE
[FALSE-POSITIVE] bcpzonasegurabeta.viabcp.com

### ISSUE THREAD

**Issue by saqrasdave** [Ultimate-Hosts-Blacklist/whitelist#111]
hello
the following site is blocked `https://bcpzonasegurabeta.viabcp.com/`

`bcpzonasegurabeta.viabcp.com` It's a legimate bank website of credit bank from  Peru (BCP)

**Comment by smed79** [comment]
Hello, 

blocked by which list?

**Comment by dnmTX** [comment]
Confirming the domain in question it's not blocked by any of the lists in Ultimate-Hosts...
....therefore CLOSING as it's not our problem.
