### ISSUE TITLE
[VirusTotal] cutt.ly

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/whitelist#115]
**Domains or links**
* http://cutt.ly/

**More Information**
I don't have time yet so can you please take a look at this for me?
I got the following per email. Thanks!

```
Hey folks,

Our client who owns 

http://cutt.ly/

has requested that we submit a review to you folks to remove the listing here:

https://www.virustotal.com/gui/url/d4e0ce17c1faeba6a5fad91acbcde883af34c17d35e58d643441568d60e263a8/detection

Given the nature of their URL shortening service it is likely being abused by attackers, so if you see any particularly problematic links or URL's it would be helpful if you could report those to me.

Thanks for your help,

***
******** *******, ******
```

Cheers and thanks again for everything!

P.S.: I will answer the email with a link to this issue.

**Comment by dnmTX** [comment]
@funilrys the domain is blocked in Phishing.Database. You know,Mitch @mitchellkrogza has to deal with it as it is his lists. For now is **pending**.
Just FYI VirusTotal showing the last scan was 12 hours ago and 2 malicious engines were detected.
I guess the owner of the site is right,definitely somebody taking advantage of it.
@smed79 any thoughts on the subject?

**Comment by funilrys** [comment]
@dnmTX Apparently (I missed the info), we are the `Ultimate Hosts` engine of VirusTotal :smile_cat:

**Comment by smed79** [comment]
I would reject adding to the whitelist. 

Below contact infos to request a removal from anti-virus and phishing DB
```
info @ dshield.org
malwaresubmit @ avlab.comodo.com
```

**Comment by funilrys** [comment]
Thanks everybody! I moved it to upstream.
