### ISSUE TITLE
[FALSE-POSITIVE?] 1drv.ms

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/whitelist#137]
See also: mitchellkrogza/Ultimate.Hosts.Blacklist#575
**Domains or links**
1drv.ms

**More Information**
How did you discover your web site or domain was listed here?
Not applicable, not my web site

**Have you requested removal from other sources?**
Not applicable, internal lists

- https://github.com/Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/domains.list
- https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database/blob/master/domains.list

**Additional context**
1drv.ms is a redirect service for microsoft office shares

**Comment by smed79** [comment]
@mitchellkrogza Can you fix this from your side.

**Comment by mitchellkrogza** [comment]
Whitelisted

**Comment by dnmTX** [comment]
Closing as RESOLVED. Thank you Mitch @mitchellkrogza  and @smed79  👍
