### ISSUE TITLE
[FALSE-POSITIVE?] d1f8f9xcsvx3ha.cloudfront.net d3e1078hs60k37.cloudfront.net

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/whitelist#138]
Looks like we are blocking all of Cloudfront due to Smed79 blocking all of Cloudfront https://github.com/smed79/blacklist/blob/master/hosts/cloudfront.txt

I posted an issue for smed79 to unblacklist Cloudfront, but if he says no we might need to consider other alternatives.

Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally

Not all Cloudfront is Ads

We should not be blocking it everywhere.

![image](https://user-images.githubusercontent.com/9235633/79360865-83776400-7f12-11ea-86d3-3fbaa1a0db96.png)
![image](https://user-images.githubusercontent.com/9235633/79360884-8a05db80-7f12-11ea-9622-62290f780e48.png)

**Comment by llacb47** [comment]
https://github.com/smed79/blacklist/pull/1#issuecomment-615923232

**Comment by p1r473** [comment]
Ok, so the 2 domains I saw that were not ads but were actual sites were 
d1f8f9xcsvx3ha.cloudfront.net
d3e1078hs60k37.cloudfront.net

**Comment by dnmTX** [comment]
The link you posted is opening just fine on my end,i even went ahead with purchasing and it went trough. I even checked the page code and none of the mentioned domains were present anywhere.

**Comment by p1r473** [comment]
Dealt with upstream

**Comment by smed79** [comment]
@p1r473 

> I posted an issue for smed79 to unblacklist Cloudfront, but if he says no we might need to consider other alternatives.

Where I say that ?

**Comment by dnmTX** [comment]
Hehehehe, @smed79  my friend, he said: **IF HE...**. I was waiting on you here to respond otherwise this issue would've been closed long time ago. 😉 

P.S. @p1r473 just for feature reference. @smed79 is in **CHARGE** here so the so called **ALTERNATIVES** has to be approved by him.

**Comment by p1r473** [comment]
> Hehehehe, @smed79 my friend, he said: **IF HE...**.
> I was waiting on you here to respond otherwise this issue would've been closed long time ago. 😉
> 
> P.S. @p1r473 just for feature reference. @smed79 is in **CHARGE** here so the so called **ALTERNATIVES** has to be approved by him.

@smed79 Haha, IF you said no
No problem, I have whitelisted cloudfront.net on my local whitelist

@dnmTX However, I do think we would still want to whitelist d3e1078hs60k37.cloudfront.net as sometimes it just hosts non-malicious icons.

Here is an icon image on a website I was browsing that failed to load due to us blocking Cloudfront:
https://d3e1078hs60k37.cloudfront.net/site_files/images/icons/mv-all-icon.svg This made the website not look as great due to broken images, and it wasn't an ad.
