### ISSUE TITLE
[FALSE-POSITIVE?] - MaxMind

### ISSUE THREAD

**Issue by alexwasserman** [Ultimate-Hosts-Blacklist/whitelist#141]
**Domains or links**

maxmind.com
dev.maxmind.com
support.maxmind.com

**More Information**

Updating suricata config to download maxmind db and discovered it's blocked.

**Have you requested removal from other sources?**

No

**Additional context**

maxmind DB is a commercial database of geolocations for IPs for use with anti-fraud, anti-spam, etc tooling.

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
Ok  Alex @alexwasserman. Only one of the domains that you listed above is blocked here: `maxmind.com` 
and it comes from one of our trusted sources. You need to open a [ISSUE](https://gitlab.com/quidsup/notrack-blocklists/-/issues) there and discuss it further with the curator.
And just to confirm,the rest of the domains that you listed:
`dev.maxmind.com`
`support.maxmind.com`
are not blocked here.
Let us know of the @quidsup's decision. Good luck 👍

**Comment by alexwasserman** [comment]
Yes, I added the other two because they're party of the same entity, and should be whitelisted along with it, if it were being whitelisted.

I've raised the ticket with quidsup.

Thanks.

**Comment by smed79** [comment]
https://gitlab.com/quidsup/notrack-blocklists/-/issues/22

**Comment by p1r473** [comment]
https://github.com/lightswitch05/hosts/issues/163

**Comment by dnmTX** [comment]
Closing this as RESOLVED in UPSTREAM.

@p1r473  not sure why you posted this considering that all of the `mixmind.com` (sub)domains are in his AGGRESSIVE list which is not in rotation here so it's kind of irrelevant,don't you think?

**Comment by p1r473** [comment]
@dnmTX yea was just posting to reference that they are in aggresive list and issue is closed
