### ISSUE TITLE
[FALSE-POSITIVE] pochta.ru

### ISSUE THREAD

**Issue by UserDmitry** [Ultimate-Hosts-Blacklist/whitelist#142]
**Domains or links**
pochta.ru

**More Information**
I use hosts file, and when I tried to check delivery status on pochta.ru, name  was not resolved.

**Have you requested removal from other sources?**
No

**Additional context**
This is a Russian Post web site.

**Comment by UserDmitry** [comment]
white listening process? I did not do this....

**Comment by dnmTX** [comment]
@UserDmitry  please report this directly to the list's owner:  `wduk10@hotmail.com` and if you don't get any response within a week or so let me know and i'll whitelist it here.

**Comment by UserDmitry** [comment]
wduk10@hotmail.com is not responded

**Comment by dnmTX** [comment]
@UserDmitry  whitelisted here. Update your lists tomorrow or so and should be gone.
Thank you for the report 👍 
Closing as **resolved**
