### ISSUE TITLE
[FALSE-POSITIVE?] www.ig.com.br

### ISSUE THREAD

**Issue by spirillen** [Ultimate-Hosts-Blacklist/whitelist#144]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.
`www.ig.com.br`

**More Information**
How did you discover your web site or domain was listed here?
1. Was working on the rpz conversion of https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/
2. Other .....

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.

<https://www.mypdns.org/T881#10509>, `whitelisted`

**Additional context**

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
NOTE to MYSELF: Related to #147
