### ISSUE TITLE
We need to remove hostsfile.mine.nu/hosts0.txt 

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/whitelist#147]
Hi all,
We are using a list: https://hostsfile.mine.nu/hosts0.txt 
In this list are many false positives that I have reported, with no response.
I don't report these to you guys as I try to always go upstream.
For example: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/132
> 
> 
> Unfortunately, no response after two months.

Here are what I have reported and when that are STILL false positive on his (and so OUR ) list!
platform.twitter.com Mar 17 - breaks some tweets embedded in articles in Google News app on Android
3p.ampproject.net Apr 3 - breaks AMP-powered Google News articles
goldmoney.com  Apr 7 - site that sells gold
www.goldmoney.com Apr 7 - site that sells gold
mene.com March 25 - site that sells jewelry
rawgit.com April 27 served files from raw.githubusercontent.com (looks like its on his list but not ours, so we must have whitelisted locally)
getpocket.com www.getpocket.com api.getpocket.com - May 1 - extension to save articles to read later
yastatic.net - May 18 - hosting static assets for cloud email client Yandex.Mail
ea.com - May 19 - gaming community
www.icq.com icq.com - May 26- chat client
res.cloudinary.com - May 29 - hosting static images in the cloud
a-000*.a-msedge.net - June 2 - CNAME for www.MSN.com
no-ip.org - June 3 - dynamic domain provider
ign.com - gaming site

**Comment by llacb47** [comment]
Yeah, I have experienced many false positives with `mine.nu` as well. 

List:

```
17173.com
3p.ampproject.net
a-0001.a-msedge.net
ak.imgfarm.com
apps.skype.com
cdn.rawgit.com
cdns.gigya.com
clustrmaps.com
completion.amazon.com
consent.cookiebot.com
cse.google.com
d17fy28x8ov4h8.cloudfront.net
d1z2jf7jlzjs58.cloudfront.net
d2c8v52ll5s99u.cloudfront.net
d3tsytm1wtjqo2.cloudfront.net
dot.tk
ebates.com
excite.com
freespeechcoalition.com
gamespot.com
geo3.ggpht.com
go.divx.com
hubpages.com
ign.com
images.sohu.com
img.sparknotes.com
img.tfd.com
inc.com
joblo.com
kiwifarms.net
m.hotmail.com
media.complex.com
nextdoor.com
p.typekit.net
platform.twitter.com
polyfill.io
pr0gramm.com
promotions.newegg.com
rawgit.com
res.cloudinary.com
s.marketwatch.com
s.telegraph.co.uk
sls.update.microsoft.com.akadns.net
sohu.com
spclient.wg.spotify.com
traffic.alexa.com
vid.pr0gramm.com
www.17173.com
www.alexa.com
www.buydomains.com
www.ebates.com
www.excite.com
www.freenet.de
www.hubpages.com
www.limasky.com
www.slickdeals.net
www.weatherbug.com
yandex.ru
yastatic.net
```

**Comment by dnmTX** [comment]
Thanks for the report guys. 
We already have few issues open from the same list but i honestly didn't know that the situation is that bad.
I fully agree that due to lack of ANY support and the numerous false-positives the list needs to GO!

**PING @funilrys**. If there are no objections from your side please proceed with the removal.
From what we all see so far i don't think there are any real benefits to keep it.
Thank you 👍

**Comment by funilrys** [comment]
Thanks for your patience. It's done. It will be removed from the central repository on the next update.

Stay safe and healthy.
Nissar

**Comment by p1r473** [comment]
Thanks!
