### ISSUE TITLE
[FALSE-POSITIVE?] *ionicframework.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/whitelist#151]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.
*ionicframework.com

**More Information**
How did you discover your web site or domain was listed here?

- HostsVN - unknown reason
- https://hosts.ubuntu101.co.za/app/contents/ says also in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt but can't find it here @funilrys 

**Have you requested removal from other sources?**
No because I cannot speak vietnamese

**Additional context**
Currently I see no reason why the project site of the ionic framework was blocked.

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
> No because I cannot speak vietnamese

@Somebodyisnobody !  The repo owner @bigdargon speaks and understands english perfectly. 
 It looks like a legitimate web app platform so please report it there for removal.

**Comment by funilrys** [comment]
This may be a problem in our infrastructure. We should probably completely clean those repositories if they really are not into upstream.

For the record (if I'm not around): 
To clean everything, delete all `*.json` file (BUT NOT `info.json`) and delete `output/continue.json`.

**Comment by dnmTX** [comment]
@funilrys  the reported domains are currently present in the [original list](https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts).

>  completely clean those repositories if they really are not into upstream

Can clarify that. I don't see any problems with the mention list/repo but there are others that needs fixing(for a long time now) due to failing to filter properly and not being updated.

**Comment by funilrys** [comment]
@dnmTX Let's start a cleanup process for all those repositories which are failing to filter. You have the right to do it!

Most of those builds which are not starting are because of the huge size of the `{whois_db,inactive_db}.json` files. So let's clean them up completely (as explained above).

In the future, we will have a central (MariaDB) database somewhere which will store everything so this won't be a problem anymore. Until then, let's just start a cleanup to see if the problem is software/code (our own tool) or huge memory usage because of the JSON databases. If it's software/code, I'll fix it! Otherwise, well, I will have to accelerate the switch to a proper database. 

Thanks for everything @dnmTX !

**Comment by dnmTX** [comment]
@funilrys  ok,i'll start the cleaning process ASAP. Please,keep an eye on the progress,let me know if i missed anything.
We need to fix that fast now that you have the DNS server up and running which will be rendered useless if those lists don't filter properly.

**Comment by Somebodyisnobody** [comment]
> 
> 
> @funilrys the reported domains are currently present in the [original list](https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts).
> 
> > completely clean those repositories if they really are not into upstream
> 
> Can you clarify that. I don't see any problems with the mention list/repo but there are others that needs fixing(for a long time now) due to failing to filter properly and not being updated.
> 
> P.S. Well...i just checked and it turns out [hostsVN](https://github.com/Ultimate-Hosts-Blacklist/hostsVN) is also failing to filter.

I never denied that either. The problem is rather that entries appear in the search which appear in another list (not hostsVN). See screenshots.
![Searchresult](https://user-images.githubusercontent.com/35230554/92646295-7eaeb480-f2e6-11ea-9ec8-6d6687ba101e.png)
![adservers txt](https://user-images.githubusercontent.com/35230554/92646297-7fdfe180-f2e6-11ea-9899-01abcf2b3d55.png)

**Comment by Somebodyisnobody** [comment]
It's not blocked by anudeepND, this is just a cache error or a corrupted index in our search engine. The domain is listed on the vietnamese speaking repository hostsVN ([here line 1520](https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts)) which is maintenanced by @bigdargon. As also the issues are in vietnamese I am unable to create an issue 😉

**Comment by dnmTX** [comment]
**PING** @bigdargon ! You mind look in to this issue please. Also it will be very helpful the english speaking users to be able to open a issue in your repo. Thank you 👍

**Comment by bigdargon** [comment]
@Somebodyisnobody Sorry about this false positives.  I will repair it within 3 hours, it's early morning in Vietnam.

@dnmTX Thank you for mentioning me!

**Comment by anudeepND** [comment]
Maybe it's a cache issue, this domain was removed 11 days ago in https://github.com/anudeepND/blacklist/commit/d6e6b629a6e4a7d9abb6d6b5fd35e22c69e05fb7 and closed this [issue](https://github.com/anudeepND/blacklist/issues/108).

**Comment by Somebodyisnobody** [comment]
Thank you both. Now all steps are taken and the domains are no longer blacklisted so I'll close this issue
