### ISSUE TITLE
[FALSE-POSITIVE?] txxx.com (NSFW)

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/whitelist#156]
**Domains or links**
`txxx.com` `www.txxx.com` (NSFW)

**More Information**
How did you discover your web site or domain was listed here?
Tried to visit ;)

**Have you requested removal from other sources?**
https://github.com/EnergizedProtection/block/issues/640
https://github.com/mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO/issues/4
https://github.com/joeylane/hosts/issues/5

**Additional context**
XXX streaming site

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
@funilrys the list that contain the domain in question is one of @smed79's that shouldn't be included with the rest of the lists here but has to remain just for filtering purposes.
I do believe we already discussed that in past. Could you please make the necessary changes. Thank you 👍

**Comment by dnmTX** [comment]
This was resolved with 7b36eed38dc8be50744fb64c6cdd8961637645 and can be closed.
