### ISSUE TITLE
[FALSE-POSITIVE?] eTLDs shouldn't be blocked

### ISSUE THREAD

**Issue by rusty-snake** [Ultimate-Hosts-Blacklist/whitelist#157]
Blocking a eTLD is usually a bad idea if it is done in a blacklist used by many people. It may make sense if an individual user decides to block a eTLD which is frequently used by phishing domains and he will never visit legitimate domains on this eTLD because of language/county/interest/… . Moreover a eTLD entry in a hosts file is useless since it is not expanded.

eTLDs currently "blocked":

```
zapto.org
site
s3.us-east-2.amazonaws.com
s3-us-west-2.amazonaws.com
redirectme.net
pp.ru
net.ar
mu
leadpages.co
in
hopto.org
group
fr
domains
bet
be
ad
```

The actual issues: Software such as dnsmasq or µBlock origin does expand on (sub-)domains. Meaning if you import the UHB into uB, https://www.gouvernement.fr/ (for example) will be blocked.

**Have you requested removal from other sources?**

no

**Comment by dnmTX** [comment]
@funilrys did you get this sorted out yet or it's still pending?

**Comment by funilrys** [comment]
@dnmTX Still pending. Added to my new workflow management tool.

**Comment by funilrys** [comment]
Should be better now.
