### ISSUE TITLE
[FALSE-POSITIVE?] Windows Weather application no connection to service

### ISSUE THREAD

**Issue by sppmasterspp** [Ultimate-Hosts-Blacklist/whitelist#159]
When I use your domain block list filter I'm unable to use the Weather application in Windows 10. It just says there is no connection probably because a domain is blocked. Is this communication considered as spy or telemetry or it's just wrong addition to the list.

**Comment by spirillen** [comment]
It's is [TrackWare](https://www.mypdns.org/w/trackware/) :smiley: so there could be a close relation to that :+1: 

May I suggest you have a look out of your windows instead :sun_behind_small_cloud:

**Comment by sppmasterspp** [comment]
Nice joke @spirillen , I like it. Here it's really cold outside at the moment and I don't like to open the windows and use my nose as a probe to measure the temperature.
But at least, does anyone know the DNS associated with this service,

**Comment by dnmTX** [comment]
@sppmasterspp did you find out which domain(s) causing your issues yet? 
Whithout that info no one here will be able to provide you with any assistance.

**Comment by sppmasterspp** [comment]
> 
> 
> @sppmasterspp did you find out which domain(s) causing your issues yet?
> Without that info no one here will be able to provide you with any assistance.

No I didn't find it sorry. This filter seem to be very in-depth and exhaustive but in Windows I even get a message that I'm not connected to the Internet (with network icon showing no connection) which is a bit inconvenient for me but still confusing to the others using the PC. So I simply will no use it.
You can close this.
Thanks for your work.

**Comment by dnmTX** [comment]
Thanks for the prompt response @sppmasterspp and Good Luck 😃 👍 
Closing....
