### ISSUE TITLE
[FALSE-POSITIVE?] redirector.gvt1.com

### ISSUE THREAD

**Issue by aravindvnair99** [Ultimate-Hosts-Blacklist/whitelist#160]
Google uses this domain to serve updates to Chrome, Android, Android Studio, Chrome extensions. There is no reason to block this.

**Comment by spirillen** [comment]
> Google uses this domain to serve updates to Chrome, Android, Android Studio, Chrome extensions. There is no reason to block this.

?? and for blocking spyware?? don't forget chrome is spyware/malware.. used to collect personal identifiable data about you. The "programs" are pure bait.

**Comment by aravindvnair99** [comment]
> > Google uses this domain to serve updates to Chrome, Android, Android Studio, Chrome extensions. There is no reason to block this.
> 
> ?? and for blocking spyware?? don't forget chrome is spyware/malware.. used to collect personal identifiable data about you. The "programs" are pure bait.

Well @spirillen, that's one way to look at it. But if someone is so privacy-focused, they wouldn't be using Chrome or Android in the first place. There are more privacy-focused alternatives out there. It's a choice that people can make. :)

**Comment by spirillen** [comment]
And they are in there full democratic right to do so :smiley: , I would just mention it for those (which is the majority) who don't know it, and that there is a relation between the blocking of it (As this list is anti: spyware, tracking, adware) so it by all rights are listed, If a user then chooses to whitelist it themself, well, they where warned.  And 
_**Personally**_ I find it rather counterproductive to whitelist spyware, adware, trackware etc if a producer claims to protect the lists users against this.

**Comment by dnmTX** [comment]
@aravindvnair99 the domain in question is already removed from here along with the two abandoned lists containing it.
Thanks for the report 👍   Closing....
