### ISSUE TITLE
[FALSE-POSITIVE?] s1.sentry-cdn.com

### ISSUE THREAD

**Issue by aravindvnair99** [Ultimate-Hosts-Blacklist/whitelist#163]
Blocking `s1.sentry-cdn.com` messes up the sign-up process.

![image](https://user-images.githubusercontent.com/22199259/110478707-a1414f00-810a-11eb-83f4-d040ce24b730.png)

**Comment by smed79** [comment]
@aravindvnair99 

> **Have you requested removal from other sources?**
> Please include all relevant links to your existing removals / whitelistings.

You should report first the issue here https://github.com/lightswitch05/hosts/issues

see also https://github.com/lightswitch05/hosts/issues/58 & https://github.com/lightswitch05/hosts/commit/bfc325a8eecb92141763439471d185631734b22c

**Comment by aravindvnair99** [comment]
> @aravindvnair99
> 
> > **Have you requested removal from other sources?**
> > Please include all relevant links to your existing removals / whitelistings.
> 
> You should report first the issue here https://github.com/lightswitch05/hosts/issues
> 
> see also [lightswitch05/hosts#58](https://github.com/lightswitch05/hosts/issues/58) & [lightswitch05/hosts@bfc325a](https://github.com/lightswitch05/hosts/commit/bfc325a8eecb92141763439471d185631734b22c)

@smed79 Here's something: https://github.com/StevenBlack/hosts/issues/568

**Comment by dnmTX** [comment]
@aravindvnair99 as @smed79 already pointed,you can open a issue upstream and argue your case with the list mintainer there.
Other then that i can assure you that we will NOT be whitelisting any Sentry domains here.
