### ISSUE TITLE
[FALSE-POSITIVE?] continuum.dds.microsoft.com

### ISSUE THREAD

**Issue by aravindvnair99** [Ultimate-Hosts-Blacklist/whitelist#164]
This domain is required for `Your Phone Companion` to work. Else it will be stuck on "connecting to PC" and "connecting to phone"

**Comment by dnmTX** [comment]
@aravindvnair99  stand by,we need to remove one of the lists here first that is no longer maintained from upstream and contains most of the reported by you false-positives and will sort out the rest.

**Comment by mitchellkrogza** [comment]
+1 for removal

**Comment by dnmTX** [comment]
**ping @lightswitch05** would you mind look in to it as your list is the other one that has the reported domain in it.
Just for reference @crazy-max [moved it to his extra list](https://github.com/crazy-max/WindowsSpyBlocker/commit/7504f14d8fa114fb600f1f22cd1ea61a5cf513e3) very likely for the same reason.
It's a legit false-positive request. Thank you 👍
