### ISSUE TITLE
akubebas.com

### ISSUE THREAD

**Issue by 3xploiton3** [Ultimate-Hosts-Blacklist/whitelist#17]
#whitelist akubebas.com

from indoxxi.bz, video cannot load

**Comment by funilrys** [comment]
Note for self:
```
> GET / HTTP/1.1
> Host: akubebas.com
> GET / HTTP/2
> Host: indoxxi.cx
```

**Comment by dnmTX** [comment]
@funilrys  i took the liberty to investigate this one and despite the fact that the reported domain delivers only fonts to that particular website:
![Capture](https://user-images.githubusercontent.com/34774426/56305179-5a58a380-6105-11e9-8d69-5c46427d7141.PNG)

in other instances delivers coin mining scripts and was blocked by [ZeroDot1](https://gitlab.com/ZeroDot1/CoinBlockerLists/blob/master/hosts#L2714) for a reason:
![coinhive](https://user-images.githubusercontent.com/34774426/56305431-e66acb00-6105-11e9-8261-1da6eb997baf.PNG)

Whitelisting it globally is out of the question on this on this one.If OP is willing to risk exposing his system to mining scripts he can remove it on his end.

**Comment by dnmTX** [comment]
@funilrys  i just want to make sure that we're on the same page about this issue based on my comment above ☝️  before i close it.

**Comment by funilrys** [comment]
Opinion shared @dnmTX.
