### ISSUE TITLE
[list removal] number of non existent lists for removal 

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/whitelist#170]
@funilrys to your attention:

* SERVICE SUSPENDED ( msg. when using the raw link provided ):
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List-High
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List-Medium
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List

* DOESN'T EXIST ANYMORE:
https://github.com/Ultimate-Hosts-Blacklist/BarbBlock-filter-list
https://github.com/Ultimate-Hosts-Blacklist/hpHosts---GRM

* Ransomware Tracker has been discontinued on Dec 8th, 2019 (raw link msg.)
https://github.com/Ultimate-Hosts-Blacklist/ransomwaretracker.abuse.ch

*********************************************************************************

* The list doesn't exist anymore at the raw link provided but all the domains from it are still present here due to probably
failed filtering and fetching the new content. I would highly suggest due to the value of the list to **preserve it**(remove the raw link and do whatever else is necessary) while it's still intact here and maintain it ourselves ❗ ❗ ❗ 
https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List-High ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List-Medium ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/ransomwaretracker.abuse.ch ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/BarbBlock-filter-list ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/hpHosts---GRM ✅

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com ✅

**Comment by funilrys** [comment]
All right, deleted everything except the last one which - as mentioned in the linked commit - is on our own.
