### ISSUE TITLE
[FALSE-POSITIVE?] boards-api.greenhouse.io

### ISSUE THREAD

**Issue by aravindvnair99** [Ultimate-Hosts-Blacklist/whitelist#171]
Greenhouse is an applicant tracking system and recruiting software that is designed to help make companies great at hiring and hire for what's next.

Many companies use it, and it shouldn't be blocked. Example of broken page: https://www.knock.com/careers#current-openings

**Comment by dnmTX** [comment]
@aravindvnair99 and the answer is the same as #163. 
If you are not planing too open a issue there and discuss it with the list's owner,simply close this one(or i will)
The list that domain is comming from is one of the most reputable here and we all respect the hard work the owner of the list put in it every day,and definitely not go against it....on your word.

P.S. And for the feature,**please**,don't ignore the issue template where is simply explained what is this here,where is all comming from,how to find out where is comming from and therefore contact it !!!!!
