### ISSUE TITLE
[FALSE-POSITIVE?] stats.stackexchange.com

### ISSUE THREAD

**Issue by aravindvnair99** [Ultimate-Hosts-Blacklist/whitelist#173]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.

stats.stackexchange.com

**More Information**
How did you discover your web site or domain was listed here?

I have added `https://hosts.ubuntu101.co.za/domains.list` in my Pi-hole. I found it by using the query feature.

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.

No, I could only find it in this list as per the output given by my Pi-Hole.

**Additional context**

That's a normal community. Felt it's a false positive.

**Comment by spirillen** [comment]
do you have any clue what this domain is used for @aravindvnair99  ??

**Comment by aravindvnair99** [comment]
> do you have any clue what this domain is used for @aravindvnair99 ??

@spirillen Yes, I do. It's one of the sub-communities under the `Science` category of [Stack Exchange](https://stackexchange.com/) called "Cross Validated" for people interested in statistics, machine learning, data analysis, data mining, and data visualization and hence a false-positive.

**Comment by dnmTX** [comment]
@aravindvnair99 doesn't look like the mentioned domain is in our database anymore. Several non existent lists were just removed
(see #170) and probably was there as far as i can tell.
Give it couple days and update your list. Let me know how it goes. Thanks 👍
