### ISSUE TITLE
[FALSE-POSITIVE?] 

### ISSUE THREAD

**Issue by ososandy** [Ultimate-Hosts-Blacklist/whitelist#177]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.

**https://www.airbnb.com.au/**

**More Information**
How did you discover your web site or domain was listed here?
1. Website was hacked
2. Other ..... I see no reason to blacklist a very popular accommodation booking website.

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.

**Additional context**

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
Thanks for the report @ososandy. Definitelly false-positive.
**Ping** @funilrys  or @mitchellkrogza  it's listed in Phishing.Database and will wait for removal.

Also @funilrys the [REPO HERE](https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database) is messed up and will need your attention for sure. One thing is the list(s) are not updating,another is that there is only one list at the present(volatile.list) who is completely empty. 
Many other repos here also stoped updating,so mines as well check all over. Thanks 👍
