### ISSUE TITLE
[whitelist candidate] oload.*

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/whitelist#18]
@funilrys didn't want to create PR just not to messed up something(regex is required on this one) so i'll let you do it.
`oload.*` domains are part of `openload.*` and in certain lists some of them are blocked.
For reference see [youtube-dl's openload.co extractor](https://github.com/ytdl-org/youtube-dl/blob/8428fdccf2dad7667cf53db449282b56dbbfa3ef/youtube_dl/extractor/openload.py#L246)
Thank you 👍 

EDIT: also add `*.oloadcdn.net` (regex required on this one as well).Those domains are used to host the content. Including here screenshot from my adblocker to see that it's been whitelisted by them as well.
This one is just in case of some possible feature blacklisting.
![Capture](https://user-images.githubusercontent.com/34774426/56181680-2467d200-5fd4-11e9-8a51-38b95f8ed3fa.PNG)

**Comment by smed79** [comment]
below all known openload mirrors
```
oladblock.me
oladblock.services
oladblock.xyz
oload.cc
oload.cloud
oload.club
oload.download
oload.fun
oload.info
oload.live
oload.site
oload.space
oload.stream
oload.tv
oload.win
olpair.com
openload.co
openload.pw
openloed.co
*.oloadcdn.net
```

**Comment by dnmTX** [comment]
@smed79 thanks for pitching in,didn't even know of some that you listed 👍 
@funilrys  how expensive will be to run the whitelist against the `volatile.list`(just curious)?

**Comment by funilrys** [comment]
@dnmTX It's actually cheep as the whitelisting tool is quiet fast :smile: 

As example for `www.shalla.de` which has over 1 million + of entries from the [central repo build](https://travis-ci.org/mitchellkrogza/Ultimate.Hosts.Blacklist/jobs/520836671#L588-L589):
```
2019-04-16 16:01:20,486 - INFO -- Starting whitelisting of 'www.shallalist.de'.
2019-04-16 16:01:43,783 - INFO -- Finished whitelisting of 'www.shallalist.de'.
```

**Comment by dnmTX** [comment]
wow,that's fast. I just checked other lists and it takes like 3 sec. at most.
Well..you want to start running the witelist against the `volatile.list` and see how it goes?
If you do i might need to go trough the list again,some reported domains from what i can remember were very questionable as they were reported blindly without any proof.Anyway you'll get the last word on the changes if any.

**Comment by funilrys** [comment]
I trust your inputs + they are top level domains + they don't look that harmful. 
Later next year I'll do some deep analytic with the data so we will see for the subdomains :smile_cat: 

Deployed will be into the next build(s) from now.

**Comment by dnmTX** [comment]
Great,thanks.I'll keep you posted if any issue(s) arise 👍

**Comment by dnmTX** [comment]
These two so far are on my questionable list:
`teredo.ipv6.microsoft.com` -everywhere you search it's recommended the teredo protocol to be disabled for security purposes. IPv6 works without it,no issues there and it was reported blindly without any proof.
`clients5.google.com` -this one brings only ads(personal observations).It's blocked on my end and so far so good.

**Comment by smed79** [comment]
https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/55d9d979c6bffd5d7d06acb550f0f7d4e39cf14e/domains.list#L539

@funilrys Without a TLD ?

> clients5.google.com -this one brings only ads

@dnmTX  Not only ads, for example "webstore review widget"
https://clients5.google.com/webstore/widget/review/cfhdojbkjhnklbpkdaibdccddilifddb

**Comment by dnmTX** [comment]
@smed79 thanks for the input,well,it's generic domain so i guess it has to stay 👍

**Comment by dnmTX** [comment]
@funilrys there are many sub-domains blocked in various lists that are part of `s3.amazonaws.com` and you have it listed:  [s3.amazonaws.com](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/8a25bd70b0601ba6bc2166f9faf239d746055ac9/domains.list#L633). Just wondering what exactly is covered,don't really like the idea of whitelisting those sub-domains as they're all blocked for a reason.

**Comment by dnmTX** [comment]
[adwords.google.com](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/8a25bd70b0601ba6bc2166f9faf239d746055ac9/domains.list#L24)
![What Is Google AdWords  How the AdWords Auction Works](https://user-images.githubusercontent.com/34774426/56308531-1e294100-610d-11e9-9302-4760527dd219.png)

Kind of confused on why is this one whitelisted 🤔

**Comment by smed79** [comment]
added `oload.services`/  https://github.com/Ultimate-Hosts-Blacklist/whitelist/pull/19

**Comment by dnmTX** [comment]
@smed79  i've spotted couple blocked domains in [anudeepND's lists](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt):
`tt2.oload.win`
`tt1.oload.win`
Are they part of `openload.co` too? If they're some regex adjustment is needed for all `oload.*` domains for sure. Can you please research as much as you can and advise.Thanks.

**Comment by smed79** [comment]
> Looks like everything that starts with tt1.* and tt2.* is where they hosting the ads

openload use `tt1` and `tt2` for tracking.
streamango.com, streamcherry.com and fruithosts.net use `t1` for the same purpose.

**Comment by dnmTX** [comment]
Thanks @smed79 👍 
Also just as a reminder you were planing to kind of merge some of the lists that you have on filtering here.
Any ETA ????

**Comment by smed79** [comment]
@dnmTX thanks for the reminder.

> you were planing to kind of merge some of the lists

Whenever I want to work on the repo, I find myself face to an impediment.
Sorry for the delay, work in progress (_please be patient_) :

[![img](https://i.vgy.me/6n2W3S.png)](https://i.vgy.me/o4ftRr.png)

**Comment by dnmTX** [comment]
@smed79  no worries(it was just a reminder) and FYI...**patience** is my middle name 😄
