### ISSUE TITLE
[FALSE-POSITIVE?] ns2.elhacker.net

### ISSUE THREAD

**Issue by ehnwebmaster** [Ultimate-Hosts-Blacklist/whitelist#181]
>**Domains or links**
not sure if is listed right now
ns2.elhacker.net

>**More Information**
>How did you discover your web site or domain was listed here?
AdGuard

>**Have you requested removal from other sources?**
Yes:
https://github.com/blocklistproject/Lists/issues/599

elhacker.net is registered domain since 2001, contains big forum, web and blog, and ns2 is mainly a e-mail server and hosting downloads like manuals, tutorials, iso's, etc

Thank you in advance.

**Comment by mitchellkrogza** [comment]
Not listed on https://github.com/mitchellkrogza/Phishing.Database

**Comment by dnmTX** [comment]
`hosts.ubuntu101.co.za` is not accessible at the moment and i can't even check where that domain is coming from.
Thanks for checking on your end Mitch @mitchellkrogza 👍
