### ISSUE TITLE
brightcove.map.fastly.net

### ISSUE THREAD

**Issue by tonhogen** [Ultimate-Hosts-Blacklist/whitelist#186]
**Domains or links**
brightcove.map.fastly.net

**More Information**
How did you discover your web site or domain was listed here?
Brightcove player on New Zealand news website stuff.co.nz won't play any content unless the above link is whitelisted.

**Have you requested removal from other sources?**
No, the link is not blacklisted in any other blacklist I use on pihole. 

**Additional context**

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by funilrys** [comment]
No explanation. Closing.

**Comment by tonhogen** [comment]
> 

Hi, thanks for your reply, but ..... does the  'No explanation. Closing" mean that my  whitelist request is refused because of the way I raised the issue? Or is brightcove.map.fastly.net a legit blacklist entry?
In the issue I raised I mentioned: "Brightcove player on New Zealand news website stuff.co.nz won't play any content unless the above link is whitelisted."

**Comment by spirillen** [comment]
When requesting for a domain removal (whitelisting) think if the following things is present in your ticket

- Who
- when
- where
- why
- how

When these things isn't in order, there are nothing to process, there is a reason why we spend hours building and optimizing these issue templates....

**Comment by funilrys** [comment]
Correct.
