### ISSUE TITLE
[FALSE-POSITIVE?] breitbart.com

### ISSUE THREAD

**Issue by tonhogen** [Ultimate-Hosts-Blacklist/whitelist#187]
**Domains or links**
www.breitbart.com

**More Information**
How did you discover your web site or domain was listed here?
didn't load in browser 

**Have you requested removal from other sources?**
no, no other blocklists I use contain this domain.

**Additional context**
This is a news website. Even though its political stance is not mine, I don't think that blocklists should be motivated by political arguments. 

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by funilrys** [comment]
Please give it some time it is already in the whitelist list.

**Comment by tonhogen** [comment]
No worries - thanks!
