### ISSUE TITLE
[FALSE-POSITIVE?] js.pusher.com

### ISSUE THREAD

**Issue by benjamin-tang-pusher** [Ultimate-Hosts-Blacklist/whitelist#190]
**Domains or links**

- `js.pusher.com`

**How did you discover your web site or domain was listed here?**

- Reported by another user.

**Have you requested removal from other sources?**

- No

**Comment by benjamin-tang-pusher** [comment]
Thanks, will ask them.

**Comment by smed79** [comment]
@bigdargon fyi.

**Comment by smed79** [comment]
https://github.com/bigdargon/hostsVN/commit/29e0eec3acfe723e451e0efdf6c77c71a110b6d8

**Comment by bigdargon** [comment]
Done! Thanks @smed79
