### ISSUE TITLE
[FALSE-POSITIVE?] 

### ISSUE THREAD

**Issue by gusfraser** [Ultimate-Hosts-Blacklist/whitelist#191]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.
secure.livechatinc.com 

**More Information**
How did you discover your web site or domain was listed here?
Livechat services not functional when the blacklist is in place

(source: https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt) 

**Have you requested removal from other sources?**
Unsure of other sources, it's a legit domain

**Additional context**
I'm not the owner but my company uses both Livechat and blacklists; Livechat won't work unless we manually whitelist. 
Keen to understand the ultimate source of your data to investigate further in case of other false positives. 

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by funilrys** [comment]
This issue has been fixed upstream.
