### ISSUE TITLE
[FALSE-POSITIVE?] lowendbox.com

### ISSUE THREAD

**Issue by Marcus1Pierce** [Ultimate-Hosts-Blacklist/whitelist#192]
**Domains or links**

1. lowendbox.com

**More Information**
1. It's just forums website that discusses vps hosting and more

**Comment by smed79** [comment]
> **Have you requested removal from other sources?**
> Please include all relevant links to your existing removals / whitelistings.

@Marcus1Pierce repport here https://github.com/mitchellkrogza/Phishing.Database/issues
