### ISSUE TITLE
[FALSE-POSITIVE?] bkrenergy.ca

### ISSUE THREAD

**Issue by stzagadouris** [Ultimate-Hosts-Blacklist/whitelist#194]
**Domains or links**

- bkrenergy.ca 172.64.80.1

**More Information**

1. This must be a new addition, I stopped being able to access my thermostat through my app
2. I then found the IP of the company, found it in your list, tested by disabling the list and trying again and it worked

**Additional context**

Not sure how this was flagged originally, but just know it is a canadian energy company that helps manage heat pump vs furnace usage in homes. With this IP blocked the user can't use the phone app, at the very least, I'm not sure if it's stopping other comms in the background as well

**Comment by smed79** [comment]
Fixed.

Thank you for taking the time to report the issue.

**Comment by stzagadouris** [comment]
Thank you smed79, for the very fast response.
