### ISSUE TITLE
[FALSE-POSITIVE?] iubenda.com

### ISSUE THREAD

**Issue by accountiub** [Ultimate-Hosts-Blacklist/whitelist#195]
**Domains or links**

1. iubenda.com
2. cdn.iubenda.com

**More Information**

1. One of our users brought this issue to us

**Have you requested removal from other sources?**

Yes from the lists marked with a green tick here: https://blocklist-tools.developerdan.com/entries/search?q=iubenda.com

**Additional context**

 iubenda provides software solutions for legal compliance of websites and apps: our products are Privacy and Cookie Policy, Terms and Conditions, Privacy Controls and Cookie Solution to name a few. We do not track any user information, other than the consent level of the person who has agreed to that.

**Comment by smed79** [comment]
@accountiub `*.iubenda.com` is blocked in the upstream @lightswitch05 hosts.
Report the problem there, https://github.com/lightswitch05/hosts/issues

**Comment by smed79** [comment]
Continue there https://github.com/lightswitch05/hosts/issues/384
