### ISSUE TITLE
[FALSE-POSITIVE?] rt.com

### ISSUE THREAD

**Issue by myCatnip** [Ultimate-Hosts-Blacklist/whitelist#197]
**Domains or links**

1. `www.rt.com`

**More Information**

1. tried to go to the website, it doesn't belong to me.

**Have you requested removal from other sources?**

none
...

**Additional context**

I copied your host file into my host file under the assumption that this list is not a political censorship list and not some kind of "truth" list. If this is not the case but it's also a political list and truth list, then that's perfectly fine too, but please make it clear that ideology and censorship is one of the purposes of this block list.

**Comment by smed79** [comment]
@myCatnip 

Don't rush to judge, your guess can be unfair ... 
We do not practice any censorship, false positive can happen and they are quickly fixed when reported.

If you read the [README.md](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#readme) you see tha the UHB is gathered from multiple sources, tested regularly and merged into one massive file which is updated daily.

`www.rt.com` is blocked in the upstream [Wiggum27_Blockers](https://gitlab.com/Wiggum27/blockers/-/raw/master/hosts), reported [\_here\_](https://gitlab.com/Wiggum27/blockers/-/issues/1)

@funilrys 

`www.rt.com` is part of -> [Ultimate.Hosts.Blacklist/master/hosts/hosts3](https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/hosts/hosts3)
searching for `www.rt.com` at https://hosts.ubuntu101.co.za/app/contents/ returns the message "_pattern not found_".

**Comment by myCatnip** [comment]
@funilrys , thanks for the info, I assumed this wasn't the purpose of the list, I was just a tad emotional expressing my annoyance at having one of my sources of comedy and laughs blocked.

I actually looked at that upstream list after @smed79 's reply (my words were actually technically conditional with an "if", and the assumption was that it was not any of these things, but the wording was emotionally annoyed and snarky, sorry for that).

When I looked, I saw a whole batch of very dubious additions around the www.rt.com addition, most notably www.express.com which is an actual printed news paper in the UK (and another of my occasional sources of comedy), along with a few sites I'm aware of from other references to them, but don't know anything about, so I don't know if they are malicious or not.

Looks to me like some one sabotaged that upstream list recently by blacklisting a selection of content they wanted to censor for whatever reasons.

**Comment by smed79** [comment]
As we don't get any response from the upstream after a week, domain has been [whitelisted](https://github.com/Ultimate-Hosts-Blacklist/whitelist/commit/7c3510d527791c89ebfc0371e759fc63fcac9378) in our infrastructure.

> ​# End add.Risk
> down to the line:
​> # Title: Gambling hosts

All [domains](https://github.com/Ultimate-Hosts-Blacklist/whitelist/files/11154494/domains.txt) will be checked for possible false positive.

Thank you for your contribution.
