### ISSUE TITLE
pulsar.ebay.*

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/whitelist#3]
[Reported](https://gitlab.com/quidsup/notrack-blocklists/issues/2) the issue like a month ago with no response from the curator.Looks like @quidsup either stop maintaining the lists or just doesn't respond to any new issues.Either way there are few of those that need to be whitelisted due to braking of functionality.
Just a heads up.

P.S. @funilrys  just a reminder for another [false positive](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/55) not to be ignored.Thank you.

**Comment by dnmTX** [comment]
@funilrys  should i assume that in the whole filtering process the `clean.list` or any other lists involved for that matter are filtered against the **whitelist**?If it is,that's great,it would save some CPU cycles on my router as i was doing it on my end as well without being aware that's already being done.

**Comment by dnmTX** [comment]
Nice.Thanks @funilrys .I was thinking to make **feature request** about it but considering the fact that there are other issues that needs fixing first decided to wait.Will wait for update. 👍

**Comment by funilrys** [comment]
Hi @dnmTX, the code for `whitelisted.list` is written. Will be deployed soon. The system should start generating them in the coming weeks.

**Comment by dnmTX** [comment]
Hmmm,that's strange.I thought the `clean.list` was already filtered against the `whitelist`,i guess i was wrong.
For example no `pulsar.ebay.com` entrie is present in [quidsup_notrack_trackers](https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers/blob/master/clean.list)'s `clean.list` but is present in the `domains.list`

**Comment by funilrys** [comment]
Look at the https://github.com/Ultimate-Hosts-Blacklist/repository-structure and see ...

**Comment by funilrys** [comment]
Deployment started.

**Comment by quidsup** [comment]
I've removed them from my blocklist now

**Comment by dnmTX** [comment]
> I've removed them from my blocklist now

Nice....Thanks @quidsup.....It's about time though 😉
