### ISSUE TITLE
False positive phishing domain

### ISSUE THREAD

**Issue by infosec-guy** [Ultimate-Hosts-Blacklist/whitelist#40]
A valid and clean domain "demo-staging.jifflenow.com" has been falsely marked as phishing domain at https://github.com/mitchellkrogza/Phishing.Database/blob/master/phishing-domains-ACTIVE.txt

Here is the report from reputed sites:

1. Sucuri: https://sitecheck.sucuri.net/results/https/demo-staging.jifflenow.com

2. VirusTotal: 
 https://www.virustotal.com/gui/url/7af4c2c2c6ff9a8566a68222d5a7e1ce02ea2538676a1ada89ca579b875242b4/detection

Kindly remove this domain from the list.

--
Regards, 
Santosh Chachar
Principal Engineer - Information Security
Jifflenow.

**Comment by mitchellkrogza** [comment]
Thanks @infosec-guy ... @funilrys

**Comment by mitchellkrogza** [comment]
@funilrys this was a false positive that originally came in through phishtank. From Santosh's email to me earlier. 
```A few weeks back the same domain was mistakenly marked as phishing domain in Phishtank our own employee while trying to report the opposite(false negative). After requesting the same it is no marked as phishing domain anymore, you can check here  https://www.phishtank.com/phish_detail.php?phish_id=6007451```

https://www.phishtank.com/phish_detail.php?phish_id=6007451

**Comment by mitchellkrogza** [comment]
Thanks @funilrys @infosec-guy tomorrow's update to the Phishing repo's will pull the new whitelist and remove it from the new commits.

**Comment by infosec-guy** [comment]
Thanks, All.
