### ISSUE TITLE
[BUG] Whitelist Script fails when adding own whitelist -w

### ISSUE THREAD

**Issue by mitchellkrogza** [Ultimate-Hosts-Blacklist/whitelist#70]
**Describe the bug**
Passing `-w myfile.txt` crashes whitelist

`TypeError: cannot serialize '_io.TextIOWrapper' object`

https://travis-ci.org/mitchellkrogza/Phishing.Database/jobs/553764835#L271-L324

**Comment by mitchellkrogza** [comment]
removing `-m -p 60` has solved the problem so it's specifically related to multiprocessing.

**Comment by spirillen** [comment]
Hi @mitchellkrogza thx for this note :ghost:  was struggling with it :smile:
