### ISSUE TITLE
gp.se and www.gp.se

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/whitelist#81]
@denizdogan [said](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/518):
> This is the biggest newspaper in Gothenburg, Sweden and should not be blocked.

**Comment by dnmTX** [comment]
Go ahead @funilrys,whitelist it.Looks like legitimate news site.

**Comment by dnmTX** [comment]
@denizdogan confirmed and whitelisted. Thank you for you contribution.
Closing....
