### ISSUE TITLE
[FALSE-POSITIVE] atheists.org

### ISSUE THREAD

**Issue by macuser666** [Ultimate-Hosts-Blacklist/whitelist#91]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.

https://atheists.org/
atheists.org

**More Information**
How did you discover your web site or domain was listed here?
1. casual surfing

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.

**Additional context**
It is the official website of American atheists
https://en.wikipedia.org/wiki/American_Atheists

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by smed79** [comment]
@macuser666 which list is blocking `atheists.org`

**Comment by macuser666** [comment]
Hi

I use the following list

https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/hosts/hosts0



On 5 Sep 2019, at Thursday 5 September 201923 h 50, smed79 <notifications@github.com> wrote:

@macuser666 <https://github.com/macuser666> which list is blocking atheists.org

**Comment by macuser666** [comment]
Hi

I use the following list

https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/hosts/hosts0

[Screen Shot 2019-09-06 at 20.30.50.pdf](https://github.com/Ultimate-Hosts-Blacklist/whitelist/files/3585249/Screen.Shot.2019-09-06.at.20.30.50.pdf)

**Comment by smed79** [comment]
@macuser666 

Before using a list, I recommend that you check what the list includes and what it will block.

@funilrys

After reviewing, the domain reported above is part of the category "religion" found in [www.shallalist.de](https://github.com/Ultimate-Hosts-Blacklist/www.shallalist.de/blob/master/domains.list) list that has 55 categories and about 27 sub-categories which may or may not be used for black or whitelisting by users depending on their need.

We can't use the whitelist process to help here because by default, our merged list will block a lot of useful domains (_automobile, education, finance & banking, government, imagehosting, news, social, webmail ...._).

@mitchellkrogza @dnmTX fyi.

**Comment by dnmTX** [comment]
I fully agree with @smed79 and i urge @mitchellkrogza  and @funilrys  to drop `shallalist.de` from the Ultimate-Hosts-Blacklist as going trough the categories,probably 99% are legit domains.
This is not a malware/adware etc. blocklist  but lists most likely design for people with some kind of a bias towards certain(legit) websites.
@smed79  thanks for noticing this,the info was very helpful 👍

**Comment by mitchellkrogza** [comment]
@funilrys Shalla has been a monster from day 1 indeed also seems to not even be updated anymore - http://www.shallalist.de/cgi-bin/queuelist.cgi probably best to drop this ?? your thoughts?

**Comment by funilrys** [comment]
@mitchellkrogza Good for me! Do you have a party datetime ?

**Comment by macuser666** [comment]
Hi

I didn't notice that the shallalist was included in ultimate hosts, nor that it blocked this type of domain. 

Thank you for pointing this out.

It's also probably true that shallalist is not really needed in a list like ultimate hosts.

**Comment by dnmTX** [comment]
@funilrys  let us know when i gets removed so we can close this issue.Thanks.

**Comment by mitchellkrogza** [comment]
I've given @funilrys the party date go ahead to remove Shallalist ie. the moment he has a spare minute and then it can be gone.

**Comment by funilrys** [comment]
:birthday::tada::balloon:
