### ISSUE TITLE
[Feature Request] set option all|reg|rzd for whitelist file

### ISSUE THREAD

**Issue by spirillen** [Ultimate-Hosts-Blacklist/whitelist#96]
In condition of having a scraped source list like [this](https://gitlab.com/my-privacy-dns/matrix/matrix/blob/master/source/whitelist/wildcard.list) one which all is to be prefixed with [ALL line in source-file$]

Another list would be more precise and demand only exact match to removed and then be in REG `^for line in source-file$`

in this way you should be able to run a command like

```bash
uhb-whitelist -wc -wa wildcard.list -wm domain.list -f to-white-list.list -o output.list
```

where:
- [-wa|-all] = prefix lines with `^ALL ^line$`
- [-wm|-reg] = prefix lines with `REG ^line$`
- [-wt|-rzd] = prefix lines with `RZD ^line$`
 - [-w] = match lines explicit and not like in you example where `facebook.com` will match `facebook.com and n++-level.facebook.com`

Does it make sense?

**Comment by funilrys** [comment]
In my example `facebook.com` whitelist `facebook.com` and `www.facebook.com` only.

**Comment by spirillen** [comment]
Hi @funilrys 

That's also one too many if it should be a clear mach explicit an expample of that could be...

We assume a blocking rule in an RPZ zone stating the entire zone should be blocked like

```
*.google.com  CNAME . ; spying, tracking, malicious
```

But we need to whitelist within the same zone... ex:

```
somethiing.to.passthrue.gooogle.com.pass-thru CNAME . ; We sorry but wee need this domain
*.somethiing.to.passthrue.gooogle.com CNAME . ; But we can happily block everything below that domain
```

Now it starts to matter :smile:

**Comment by funilrys** [comment]
That was written in order to avoid a huge whitelist list. It won't change. It was mainly thought and written like that because of our system which tests both `facebook.com` and `www.facebook.com`. But It's true, that people with `-wc` may not expect that behavior.

A new switch which disallows the whitelisting of `www.facebook.com` (if `facebook.com` is given) is what we need for that use case (which I find interesting).

**Comment by spirillen** [comment]
But for clarity....

Q: Does the script _ONLY_ test for ^www.some-domain.tld **_or_** do it test _fifth.fourth.third.domain.tld_ against  `fourth.third.domain.tld`

Or in short the third level ^[www] only?

**Comment by funilrys** [comment]
If `facebook.com` is given into the whitelist list, the following  are removed :

```
^www.facebook.com$
^facebook.com$
```

**Comment by funilrys** [comment]
Closing as fixed.

**Comment by spirillen** [comment]
Wooo is there a :gift: under the :christmas_tree: :santa:
