### ISSUE TITLE
[FALSE-POSITIVE] archive.org

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/whitelist#99]
**Domains or links**
archive.org (blocked)
web.archive.org (non-blocked)

**More Information**
Archive.org is an Website archive so you could access old versions of blacklisted websites. But web.archive.org isn't blocked.

I don't wanna say that archive.org is evil but for child protection reasons it makes sense to block it. So i sugesst to block both archive.org-domains or none of them (js of we.barchive.org is on archive.org so that makes also problems)

**Have you requested removal from other sources?**
no

**Additional context**

:exclamation:

We understand being listed on a list like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by dnmTX** [comment]
@Somebodyisnobody  i would suggest to trace on which list this domain belongs to and contact the curators there for further discussion.
Ultimate-Hosts-Blacklist is gathering many lists as to provide to the end user better protection and has nothing to do with how those lists are managed.
And here is really not the place for such a long discussions on who's wrong and who's right based purely on personal opinion.
I'm closing this as there is no point to start/continue debating !!!!!

**Comment by Somebodyisnobody** [comment]
Do you have an import log which source it is or do I need to crawl them manually?

**Comment by dnmTX** [comment]
@funilrys  is working on a [web tool](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/98#issuecomment-538533654) that should make it easier to trace the source of a blocked domain so either wait for it or you can try manually which will be time consuming to say the least.
